[package]
name = "start"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "start"
test = false
bench = false

[dependencies]

[profile.release]
panic = "abort"
lto = true
opt-level = "s"

[profile.dev]
panic = "abort"
